#!/usr/bin/env node

const temp = require('temp')
const gulp = require('gulp')
const stylus = require('gulp-stylus')
const connect = require('gulp-connect')
const createHTML = require('create-html')
const fromString = require('from2-string')
const source = require('vinyl-source-stream')
const browserify = require('browserify')
const fs = require('fs')

temp.track()

let cwd = process.cwd()
let out = temp.mkdirSync()

gulp.task('css', () => {
  return gulp.src(`${__dirname}/styles/**.styl`)
    .pipe(stylus())
    .pipe(gulp.dest(`${out}/css`))
    .pipe(connect.reload())
})

gulp.task('html', () => {
  let stylesheets = ['main.css', 'deck.css']
    .map(s => `<link rel="stylesheet" href=css/${s}>`)
    .join('\n')

  let html = {
    title: 'nearForm Presentation',
    script: 'bundle.js',
    head: stylesheets,
    lang: 'en'
  }

  return fromString(createHTML(html))
    .pipe(source('index.html'))
    .pipe(gulp.dest(out))
    .pipe(connect.reload())
})

gulp.task('markdown', () => {
  return gulp.src(`${cwd}/deck.md`)
    .pipe(gulp.dest(`${out}`))
    .pipe(connect.reload())
})

gulp.task('images', () => {
  return gulp.src(`${__dirname}/images/**`)
    .pipe(gulp.dest(`${out}/images`))
})

gulp.task('deckImages', () => {
  return gulp.src(`${cwd}/images/**`)
    .pipe(gulp.dest(`${out}/images`))
    .pipe(connect.reload())
})

gulp.task('deckCSS', () => {
  return gulp.src(`${cwd}/deck.css`)
    .pipe(gulp.dest(`${out}/css`))
    .pipe(connect.reload())
})

gulp.task('js', () => {
  // remark isn't resolvable by require()
  let remarkBase = `${__dirname}/node_modules/remark/src`

  let extReqs = fs.readdirSync(`${remarkBase}/remark/components`)
    .map((name) => {
      let path = `${remarkBase}/remark/components/${name}/${name}.js`

      return {
        file: path,
        expose: `components/${name}`
      }
    })
    .concat([
      {
        file: `${remarkBase}/remark.js`,
        expose: 'remark'
      }
    ])

  return browserify(`${__dirname}/app.js`)
    .require(extReqs)
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(gulp.dest(out))
})

gulp.task('serve', () => {
  connect.server({
    root: out,
    livereload: true
  })
})

gulp.task('watch', () => {
  gulp.watch(`${cwd}/deck.css`, ['deckCSS'])
  gulp.watch([`${cwd}/deck.md`], ['markdown'])
  gulp.watch([`${cwd}/images`], ['deckImages'])
})

gulp.task('default', [
  'serve',
  'html',
  'css',
  'js',
  'images',
  'deckImages',
  'markdown',
  'deckCSS',
  'watch'
])

gulp.start.apply(gulp, ['default'])
